apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lunch-cronjob
  namespace: default
spec:
  schedule: "0 8 * * 1-6" # 10am, Mon to Fri
  concurrencyPolicy: Forbid # either allow|forbid|replace
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: lunch-cronjob
              image: thesolution90/victualia-menu-crawler:latest
              env:
                - name: SLACKCHANNEL
                  value: 'someslackchannel'
                - name: SLACKWEBHOOK
                  value: 'someslackwebhook'
                - name: SLACKUSER
                  value: 'someslackuser'
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 8.8.8.8